// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package sql

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ExpBusiness struct {
	ID          int64
	Name        string
	Category    string
	SubCategory string
}

type ExpDescToBusiness struct {
	ID           int64
	Description  string
	BusinessName string
}

type ExpTransaction struct {
	ID               int64
	Identifier       string
	Type             string
	Status           string
	Date             pgtype.Timestamptz
	ProcessedDate    pgtype.Timestamptz
	OriginalAmount   float64
	OriginalCurrency string
	ChargedAmount    float64
	ChargedCurrency  string
	Description      string
	Memo             string
	Category         string
	Account          string
	CompanyID        string
	Hash             string
}
