name: Go Test

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Golang Tests
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.21.1'  # Use the version of Go your project requires

    - name: Install Atlas
      run: curl -sSf https://atlasgo.sh | sh

    - name: Check out code
      uses: actions/checkout@v3

    - name: Test
      run: go test ./...
